### PR TITLE
Code cleanup and bug fix

### PR DESCRIPTION
**Pull request by oseikuffuor1**
* Minor updates to python scripts
* Some cleanup to remove unnecessary assert and warnings
* Initialized initialized variable used for preconditioning. This fixes an issue where NaNs are obtained as a result.

### CODE REVIEW

**Review by jeanlucf22 — APPROVED** [review]

**Comment by jeanlucf22** [comment]
The following tests FAILED:

	 21 - testShortSighted (Failed)

	 32 - testMD_D72 (Failed)

Errors while running CTest

**Review by jeanlucf22 — CHANGES_REQUESTED** [review]
2 tests failures in CI

**Comment by oseikuffuor1** [comment]
@jeanlucf22 I just reviewed the branch and the tests are all passing for me. Thanks.

**Comment by Rombur** [comment]
The CI is still failing (https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/MGMOL/detail/MGMOL/71/tests/) but I don't think it's related to the PR. The cloud we are using has changed a few months ago and now they enforce memory/cpu usage. The two failing tests are using 5 cores. If possible, we should use 4.

**Review by jeanlucf22 — APPROVED** [review]

**Pull request merged**
