### PR TITLE
Modify build_pel to be consistent with other build scripts in repo

### PR DESCRIPTION
**Pull request by oseikuffuor1**

### CODE REVIEW

**Comment by Rombur** [comment]
OK to test

**Comment by Rombur** [comment]
@oseikuffuor1 you should not create a pull request from your own `release` branch. You should have created the PR from the `buildPel` branch because now once we merge this PR into `release`, you may get into trouble when you pull from `upstream/release`. I would advise you to close this PR, do a hard reset on `release` to get rid of the merge commit, and open a new PR from `buildPel`

**Comment by oseikuffuor1** [comment]
@Rombur this is actually from my fork, which I believe is common practice. Are you suggesting I do the PR from the buildPel branch off my fork directly instead? Thanks.

**Comment by Rombur** [comment]
@oseikuffuor1 Yes, exactly. The problem with what you have done right now is this. If you look at your `release` branch, you have:
```
commit 933
commit 5c7
commit b9c
```
On the main `release` branch, we have:
```
commit 933
commit ...
commit 35e
```

When we will merge this PR, the main `release` branch will be:
```
commit 933
commit ...
commit 35e
commit 5c7 <- your commit
commit b9c <- your commit
```
Now, the problem will appear when you will try to update your own `release` branch. Because the last two commits of your `release` branch are also the last two commits of the main `release` branch. Thus, git will have problem adding `commit 35e` and before to your branch. In practice, it should work because you will probably get a merge commit in your `release` branch but what you really want is a fast-forward. Otherwise the history of your `release` and the history of the main `release` will be different.

**Comment by oseikuffuor1** [comment]
@Rombur Got it. Thanks, I will make the change.

**Pull request closed without merging**
