### PR TITLE
Split the mpi communication functions

### PR DESCRIPTION
**Pull request by wjge**
The communication functions are split into two so that they no longer depend on the OMP OFFLOAD MACROs.

### CODE REVIEW

**Comment by jeanlucf22** [comment]
@Rombur Any comments about the way templated functions are declared? I am not familiar with this way of writing it.

**Comment by Rombur** [comment]
The templating looks fine however I would not merge this PR. The idea of this PR is wrong. We want the host and the device code to be as close as possible. This means that the differences between the two code paths should only happen in localized places. Instead this PR creates two different code paths on the most external functions. If there is a bug in the common part, it needs to be fixed twice.

**Comment by jeanlucf22** [comment]
@Rombur While I agree in general with your statement, it is hard to do here: there is functionality we support for CPUs using stl containers, and that we don't want to support at the moment for GPUs. So there is not so much code we could share between the two. Note that this PR is only about making GPU/CPU functionalities based on templates argument instead of compile time flags. The code duplication was already there before

**Comment by wjge** [comment]
@Rombur Is there anything wrong with CI?

**Comment by Rombur** [comment]
I disagree, this PR makes things worse that's why you are adding 300 lines of codes. I haven't looked at the PR in details but for example this code https://github.com/LLNL/mgmol/pull/160/files#diff-2fa7414609fc24fe94674a32c45294ee5d9da545e4dbb875609c8ec5a32ac6ffL1325-L1348 should be merged. You can do `memcpy` on the device and your are already working with pointers.

**Comment by Rombur** [comment]
> @Rombur Is there anything wrong with CI?

Looking into it. Damien changed some parameters in Jenkins a few days ago.

**Comment by wjge** [comment]
@Rombur We have discussed about code replication problem. I'm fine with either way. For some remaining overlapping parts (host send/receive) you pointed out, eventually they need to be replaced by cuda-aware mpi or another macro to switch between the two.

**Comment by wjge** [comment]
@jeanlucf22 If you want to use c++14, the code would look slightly better by replacing enable_if with enable_if_t, but this is a minor issue compared with the decision whether we need this PR.

**Comment by jeanlucf22** [comment]
Let's stick to C++11 for now. We need this PR in the sense that we want to have GridFuncVector to be either on CPU or GPU, and have some function implementations device dependent. But the question is: could we write it we less code duplication, and without too much work? I am not convinced of that...

**Comment by Rombur** [comment]
Github has removed a functionality that we were using. Let me close and re-open the PR to see if the problem is fixed

**Comment by Rombur** [comment]
OK to test

**Comment by Rombur** [comment]
Retest this please

**Comment by Rombur** [comment]
The CI is back on.

**Comment by Rombur** [comment]
This PR deadlocks on MAGMA without withou OpenMP offload. I had to kill the CI manually.

**Comment by jeanlucf22** [comment]
@wjge @Rombur Today I spent sometime looking into how to make this PR pass the "MAGMA" tests. I went down a long rabbit hole to realize maybe it was not a good idea to keep that MAGMA build, at least in the short term. This build is here due to the way the code evolved and is not really useful anymore as is. While a build with MAGMA but without OpenMP could still make sense (in a scenario where O(N2) ops are on cpu), it would need a lot of code modifications that we don't have time to do right now. And it would rely on some of the changes this PR in particular is trying to address: having a GridFuncVector class fully functional either on CPU or GPU.
So what I would propose for now is to turn off the MAGMA tests (in a different PR) and maybe revisit it later.

**Pull request merged**
