### PR TITLE
Add new option: Davidson with mixing coefficient

### PR DESCRIPTION
**Pull request by jeanlucf22**

### CODE REVIEW

**Comment by jeanlucf22** [comment]
@Rombur I think the clang test fails for a reason unrelated to code. Could you look at it please? Thanks.

**Comment by Rombur** [comment]
Yeah. It looks like there is no space left on the machine.

**Comment by jeanlucf22** [comment]
@Rombur shall I do a new push to relaunch the CI?

**Comment by Rombur** [comment]
Yeah it should work now

**Pull request merged**
