### PR TITLE
Add CPU and GPU implementation of del2_4th

### PR DESCRIPTION
**Pull request by Rombur**
Let's see if that speeds up the CI

### CODE REVIEW

**Comment by jeanlucf22** [comment]
@Rombur It would be nice if the test "testBatchLaph4" would call the GPU function when Offload is ON. I believe it is not anymore

**Comment by Rombur** [comment]
It's because the code works differently now. To use offload, all the data needs to be on the device which is not the case right now. I thought that Wenjun was working on that part.

**Comment by jeanlucf22** [comment]
Yes, let's wait for Wenjun's PR

**Comment by wjge** [comment]
Let me see if I can template GridFunc and fix the test issue first. It will take a while before I can get the GridFuncVector working with the memory space template.

**Comment by Rombur** [comment]
I think this PR should be merged once it passes because it speeds up the CI so much. MGMOL hogs a lot of the CI infrastructure.

**Comment by jeanlucf22** [comment]
agree

**Pull request merged**
