### PR TITLE
Writing occupation information in the restart file.

### PR DESCRIPTION
**Pull request by dreamer2368**
This is to collect some sample occupations that we can use for the test of ROM Hartree potential solver. Not exactly sure this is the right variable to save. Need a review.

### CODE REVIEW

**Comment by jeanlucf22** [comment]
There is already a function to dump the density matrix, which is the generalization of the occupation numbers when wavefunctions are not necessarily eigenfunctions https://github.com/LLNL/mgmol/blob/13b86427defbd1412c219cc4092f5eda571865c7/src/ProjectedMatrices.cc#L740

**Comment by dreamer2368** [comment]
> There is already a function to dump the density matrix, which is the generalization of the occupation numbers when wavefunctions are not necessarily eigenfunctions
> 
> https://github.com/LLNL/mgmol/blob/13b86427defbd1412c219cc4092f5eda571865c7/src/ProjectedMatrices.cc#L740

Thanks for this pointer. One question: 1D Carbyne case is fully occupied, right? I checked the 1D Carbyne restart files and they did not have `Density_Matrix` dataset. And I realized that `Density_Matrix` is saved only when the simulation is not fully-occupied case. Do you think we can release this condition and save the density matrix at any case?

**Comment by jeanlucf22** [comment]
> > There is already a function to dump the density matrix, which is the generalization of the occupation numbers when wavefunctions are not necessarily eigenfunctions
> > https://github.com/LLNL/mgmol/blob/13b86427defbd1412c219cc4092f5eda571865c7/src/ProjectedMatrices.cc#L740
> 
> Thanks for this pointer. One question: 1D Carbyne case is fully occupied, right? I checked the 1D Carbyne restart files and they did not have `Density_Matrix` dataset. And I realized that `Density_Matrix` is saved only when the simulation is not fully-occupied case. Do you think we can release this condition and save the density matrix at any case?

When no unoccupied states are used, the density matrix is simply the inverse of the Gram matrix computed from the wavefunctions. So it can be easily recomputed from the wavefunctions and saving it is not necessary

**Comment by dreamer2368** [comment]
> > > There is already a function to dump the density matrix, which is the generalization of the occupation numbers when wavefunctions are not necessarily eigenfunctions
> > > https://github.com/LLNL/mgmol/blob/13b86427defbd1412c219cc4092f5eda571865c7/src/ProjectedMatrices.cc#L740
> > 
> > 
> > Thanks for this pointer. One question: 1D Carbyne case is fully occupied, right? I checked the 1D Carbyne restart files and they did not have `Density_Matrix` dataset. And I realized that `Density_Matrix` is saved only when the simulation is not fully-occupied case. Do you think we can release this condition and save the density matrix at any case?
> 
> When no unoccupied states are used, the density matrix is simply the inverse of the Gram matrix computed from the wavefunctions. So it can be easily recomputed from the wavefunctions and saving it is not necessary

From ROM standpoint, whether it is fully occupied or not is somewhat unimportant. Especially when we're trying to implement ROM for general 'partially' occupied cases. I just want to save the density matrix somewhere and use it for testing the ROM. Trying to recompute density matrix only when the system is fully occupied, will complicate the code implementation. If you don't prefer to save the density matrix in the restart file for all cases, where would you suggest for saving the density matrix for all cases (probably with some `Control` option)?

**Comment by dreamer2368** [comment]
We will be focusing on unoccupied cases, closing this PR.

**Pull request closed without merging**
