### PR TITLE
Super sampling

### PR DESCRIPTION
**Pull request by nikwoj**
Currently only major changes are to Potentials.cc and Potentials.h

In the .h file, added new member function for supersampling. In .cc file, actually implemented new method. Also minor tweeks in .cc and .h file so that it takes in the filter option, so it knows whether to do supersampling or not.

Also had to make modifications to a bunch of other files, like MGmol.cc, Control.cc, because switched the type of basic configuration files (short to char).

Added text to KBprojectorSparse, but commented them out due to lack of time to finish them, so nothing should actually change in that file.

### CODE REVIEW

**Comment by Rombur** [comment]
ok to test

**Comment by oseikuffuor1** [comment]
Hi @nikwoj, it looks good to me, but I have some minor comments/ questions. First, could you rename the superSampling and testSuperSampling file extensions from .cpp to .cc to be consistent with the remaining files in the src directory. Also, is the testSuperSampling file meant to be in the test directory? Lastly, instead of passing a new argument "flag_filter" to Forces.h, etc, did you consider accessing it from the class member objects? That is, could you access flag_filter through the Hamiltonian object in Forces (since Potentials is an object of the Hamiltonian class)? Note that I have not fully verified that this will work. I am just wondering if you considered it. Thanks.

**Comment by jeanlucf22** [comment]
> Hi @nikwoj, it looks good to me, but I have some minor comments/ questions. First, could you rename the superSampling and testSuperSampling file extensions from .cpp to .cc to be consistent with the remaining files in the src directory. Also, is the testSuperSampling file meant to be in the test directory? Lastly, instead of passing a new argument "flag_filter" to Forces.h, etc, did you consider accessing it from the class member objects? That is, could you access flag_filter through the Hamiltonian object in Forces (since Potentials is an object of the Hamiltonian class)? Note that I have not fully verified that this will work. I am just wondering if you considered it. Thanks.

I believe the way the "flag_filter" is passed in is good, at least for now. 
Yes, .cpp shoudl be .cc.
I told @nikwoj that I would take care of integrating testSuperSampling into test suite after pull request since his internship ended last week.

**Comment by jeanlucf22** [comment]
Since @nikwoj is done with his internship, I will approve this PR as is and fix issues in another PR.

**Pull request merged**
