### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by Rombur**
Update the docker images to install gcc 9 with openmp offloading support

Blocked by #75

### CODE REVIEW

**Comment by Rombur** [comment]
@jeanlucf22 I am getting close to get this PR working, I only have a problem with the coverage left. However, not all the tests pass when using multiple threads and OpenMP see [here](https://cloud.cees.ornl.gov/jenkins-ci/job/mgmol/view/change-requests/job/PR-76/41/testReport/) but they do pass when I set `OMP_NUM_THREADS=1` see [here](https://cloud.cees.ornl.gov/jenkins-ci/job/mgmol/view/change-requests/job/PR-76/42/testReport/). Note that before we forgot to add the OpenMP flags in  many places and thus, most of the `pragma` were simply ignored. I am not sure if the current result means that there is a problem with OpenMP or not. Can you take a look.

**Comment by jeanlucf22** [comment]
Looks to me like we may have a bug there. More precisely in the function KBPsiMatrixSparse::computeKBpsi(), in the second OpenMP loop. Looking into that.

**Comment by jeanlucf22** [comment]
> Looks to me like we may have a bug there. More precisely in the function KBPsiMatrixSparse::computeKBpsi(), in the second OpenMP loop. Looking into that.

@Rombur You could actually comment out this OpenMP pragma for now. We will reactivate it when we find the bug

**Comment by Rombur** [comment]
This is ready to be merged. There are still a few warnings but I will deal with them in another PR.

**Comment by jeanlucf22** [comment]
Looks good to me!
@oseikuffuor1 Can you take a look too, in particular if anything you cared about disappeared?

**Comment by oseikuffuor1** [comment]
Looks good to me. Thanks.

**Comment by oseikuffuor1** [comment]
Since this PR involves quite a bit of work, @jeanlucf22 if you are ok with this, we can go ahead and merge it and make the correction to #75 later (i.e. change 'conv += ...' to 'conv = ...')

**Pull request merged**
