### PR TITLE
Clang tidy

### PR DESCRIPTION
**Pull request by Rombur**
I have run clang-tidy on the code. I have created one commit per options of clang-tidy so if you don't like one change, I can easily drop it. Note that `bugprone` found a real bug in the code. If you want me to run clang-tidy with different options let me know. I have tried to be conservative (I've run all the performance and bugprone options and only two modernize options)

### CODE REVIEW

**Comment by Rombur** [comment]
While working on this PR, I noticed is that you often use `using namespace std;` which I don't think it's a good idea because you never know which function you are getting. An example of that is the second commit where instead of using the c++ function you were using the c version which silently casts the `float` to a `double`. This is not dangerous in this case but it just shows that omitting `std` can yield unexpected results.

**Comment by jeanlucf22** [comment]
> While working on this PR, I noticed is that you often use `using namespace std;` which I don't think it's a good idea because you never know which function you are getting. An example of that is the second commit where instead of using the c++ function you were using the c version which silently casts the `float` to a `double`. This is not dangerous in this case but it just shows that omitting `std` can yield unexpected results.

Agree. I tried to at least avoid it in .h files. Can clang-tidy take care of that?

**Comment by Rombur** [comment]
There is an option https://clang.llvm.org/extra/clang-tidy/checks/google-build-using-namespace.html but I am not sure if it's smart enough to use `std::` where necessary or if it's just a glorified `grep`. Let me try.

**Comment by Rombur** [comment]
It just spits out warnings. It's not very different than `grep` :disappointed:

**Pull request merged**
