### PR TITLE
Threaded test for VariableSizeMatrix insert function

### PR DESCRIPTION
**Pull request by jeanlucf22**

### CODE REVIEW

**Comment by oseikuffuor1** [comment]
@jeanlucf22 this looks good to me. Would it be reasonable to test the matrix statistics for the insert test? That is, use boost_test to evaluate these statistics:https://github.com/LLNL/mgmol/blob/2b257421fd669d1e9ff5a9d186c58f197140195c/tests/testVariableSizeMatrix.cc#L140-L141 ?

**Comment by jeanlucf22** [comment]
Sure. I didn't want to touch that part since I could not quite follow what you meant to do there. Feel free to make changes in a new PR.

**Comment by Rombur** [comment]
@oseikuffuor1 is also an admin of the repo so you could both work on this PR if @jeanlucf22 has checked the box to let admin push on a PR

**Comment by oseikuffuor1** [comment]
Ok sounds good. In the variable_size_matrix test, I was not relying on threading so it was not an interesting check. However, since we are using threading for the variable_size_matrix_insert test, it will be good to check that the critical sections are respected. Something like
BOOST_TEST(mat.n() == lsize);
BOOST_TEST(mat.nnzmat() == (lsize * lsize)); 
should do it.

**Pull request merged**
